./VRPSolver data/p4.2.a.txt --cfg config/TOP.cfg &> out/p4.2.a.tex
./VRPSolver data/p4.2.b.txt --cfg config/TOP.cfg &> out/p4.2.b.tex
./VRPSolver data/p4.2.c.txt --cfg config/TOP.cfg &> out/p4.2.c.tex
./VRPSolver data/p4.2.d.txt --cfg config/TOP.cfg &> out/p4.2.d.tex
./VRPSolver data/p4.2.e.txt --cfg config/TOP.cfg &> out/p4.2.e.tex
./VRPSolver data/p4.2.f.txt --cfg config/TOP.cfg &> out/p4.2.f.tex
./VRPSolver data/p4.2.g.txt --cfg config/TOP.cfg &> out/p4.2.g.tex
./VRPSolver data/p4.2.h.txt --cfg config/TOP.cfg &> out/p4.2.h.tex
./VRPSolver data/p4.2.i.txt --cfg config/TOP.cfg &> out/p4.2.i.tex
./VRPSolver data/p4.2.j.txt --cfg config/TOP.cfg &> out/p4.2.j.tex
./VRPSolver data/p4.2.k.txt --cfg config/TOP.cfg &> out/p4.2.k.tex
./VRPSolver data/p4.2.l.txt --cfg config/TOP.cfg &> out/p4.2.l.tex
./VRPSolver data/p4.2.m.txt --cfg config/TOP.cfg &> out/p4.2.m.tex
./VRPSolver data/p4.2.n.txt --cfg config/TOP.cfg &> out/p4.2.n.tex
./VRPSolver data/p4.2.o.txt --cfg config/TOP.cfg &> out/p4.2.o.tex
./VRPSolver data/p4.2.p.txt --cfg config/TOP.cfg &> out/p4.2.p.tex
./VRPSolver data/p4.2.q.txt --cfg config/TOP.cfg &> out/p4.2.q.tex
./VRPSolver data/p4.2.r.txt --cfg config/TOP.cfg &> out/p4.2.r.tex
./VRPSolver data/p4.2.s.txt --cfg config/TOP.cfg &> out/p4.2.s.tex
./VRPSolver data/p4.2.t.txt --cfg config/TOP.cfg &> out/p4.2.t.tex
./VRPSolver data/p4.3.a.txt --cfg config/TOP.cfg &> out/p4.3.a.tex
./VRPSolver data/p4.3.b.txt --cfg config/TOP.cfg &> out/p4.3.b.tex
./VRPSolver data/p4.3.c.txt --cfg config/TOP.cfg &> out/p4.3.c.tex
./VRPSolver data/p4.3.d.txt --cfg config/TOP.cfg &> out/p4.3.d.tex
./VRPSolver data/p4.3.e.txt --cfg config/TOP.cfg &> out/p4.3.e.tex
./VRPSolver data/p4.3.f.txt --cfg config/TOP.cfg &> out/p4.3.f.tex
./VRPSolver data/p4.3.g.txt --cfg config/TOP.cfg &> out/p4.3.g.tex
./VRPSolver data/p4.3.h.txt --cfg config/TOP.cfg &> out/p4.3.h.tex
./VRPSolver data/p4.3.i.txt --cfg config/TOP.cfg &> out/p4.3.i.tex
./VRPSolver data/p4.3.j.txt --cfg config/TOP.cfg &> out/p4.3.j.tex
./VRPSolver data/p4.3.k.txt --cfg config/TOP.cfg &> out/p4.3.k.tex
./VRPSolver data/p4.3.l.txt --cfg config/TOP.cfg &> out/p4.3.l.tex
./VRPSolver data/p4.3.m.txt --cfg config/TOP.cfg &> out/p4.3.m.tex
./VRPSolver data/p4.3.n.txt --cfg config/TOP.cfg &> out/p4.3.n.tex
./VRPSolver data/p4.3.o.txt --cfg config/TOP.cfg &> out/p4.3.o.tex
./VRPSolver data/p4.3.p.txt --cfg config/TOP.cfg &> out/p4.3.p.tex
./VRPSolver data/p4.3.q.txt --cfg config/TOP.cfg &> out/p4.3.q.tex
./VRPSolver data/p4.3.r.txt --cfg config/TOP.cfg &> out/p4.3.r.tex
./VRPSolver data/p4.3.s.txt --cfg config/TOP.cfg &> out/p4.3.s.tex
./VRPSolver data/p4.3.t.txt --cfg config/TOP.cfg &> out/p4.3.t.tex
./VRPSolver data/p4.4.a.txt --cfg config/TOP.cfg &> out/p4.4.a.tex
./VRPSolver data/p4.4.b.txt --cfg config/TOP.cfg &> out/p4.4.b.tex
./VRPSolver data/p4.4.c.txt --cfg config/TOP.cfg &> out/p4.4.c.tex
./VRPSolver data/p4.4.d.txt --cfg config/TOP.cfg &> out/p4.4.d.tex
./VRPSolver data/p4.4.e.txt --cfg config/TOP.cfg &> out/p4.4.e.tex
./VRPSolver data/p4.4.f.txt --cfg config/TOP.cfg &> out/p4.4.f.tex
./VRPSolver data/p4.4.g.txt --cfg config/TOP.cfg &> out/p4.4.g.tex
./VRPSolver data/p4.4.h.txt --cfg config/TOP.cfg &> out/p4.4.h.tex
./VRPSolver data/p4.4.i.txt --cfg config/TOP.cfg &> out/p4.4.i.tex
./VRPSolver data/p4.4.j.txt --cfg config/TOP.cfg &> out/p4.4.j.tex
./VRPSolver data/p4.4.k.txt --cfg config/TOP.cfg &> out/p4.4.k.tex
./VRPSolver data/p4.4.l.txt --cfg config/TOP.cfg &> out/p4.4.l.tex
./VRPSolver data/p4.4.m.txt --cfg config/TOP.cfg &> out/p4.4.m.tex
./VRPSolver data/p4.4.n.txt --cfg config/TOP.cfg &> out/p4.4.n.tex
./VRPSolver data/p4.4.o.txt --cfg config/TOP.cfg &> out/p4.4.o.tex
./VRPSolver data/p4.4.p.txt --cfg config/TOP.cfg &> out/p4.4.p.tex
./VRPSolver data/p4.4.q.txt --cfg config/TOP.cfg &> out/p4.4.q.tex
./VRPSolver data/p4.4.r.txt --cfg config/TOP.cfg &> out/p4.4.r.tex
./VRPSolver data/p4.4.s.txt --cfg config/TOP.cfg &> out/p4.4.s.tex
./VRPSolver data/p4.4.t.txt --cfg config/TOP.cfg &> out/p4.4.t.tex
